export default{
  "message": "string",
  "target": [
    {
      "actualPrice": 0,
      "code": "string",
      "consigneeName": "string",
      "consigneePhonenum": "string",
      "createTime": "2017-05-14T11:15:13.353Z",
      "deliveryAddress": "string",
      "details": [
        {
          "actualPrice": 0,
          "actualProductNum": 0,
          "actualProductWeight": 0,
          "head": "string",
          "icon": "string",
          "name": "string",
          "productId": 0,
          "productMode": "string",
          "productNum": 0,
          "productPrice": 0,
          "productTotalPrice": 0,
          "productUnitPrice": 0,
          "productWeight": 0,
          "type": 0,
          "unit": "string"
        },
        {
          "actualPrice": 0,
          "actualProductNum": 0,
          "actualProductWeight": 0,
          "head": "string",
          "icon": "string",
          "name": "string",
          "productId": 0,
          "productMode": "string",
          "productNum": 0,
          "productPrice": 0,
          "productTotalPrice": 0,
          "productUnitPrice": 0,
          "productWeight": 0,
          "type": 0,
          "unit": "string"
        }
      ],
      "id": 0,
      "merchantName": "string",
      "orderRemark": "string",
      "paymentAmount": 0,
      "paymentStatus": 0,
      "price": 0,
      "receiverTime": "2017-05-14T11:15:13.353Z",
      "status": 0,
      "statusShowName": "string",
      "totalActualPrice": 0
    },
    {
      "actualPrice": 0,
      "code": "string",
      "consigneeName": "string",
      "consigneePhonenum": "string",
      "createTime": "2017-05-14T11:15:13.353Z",
      "deliveryAddress": "string",
      "details": [
        {
          "actualPrice": 0,
          "actualProductNum": 0,
          "actualProductWeight": 0,
          "head": "string",
          "icon": "string",
          "name": "string",
          "productId": 0,
          "productMode": "string",
          "productNum": 0,
          "productPrice": 0,
          "productTotalPrice": 0,
          "productUnitPrice": 0,
          "productWeight": 0,
          "type": 0,
          "unit": "string"
        },
        {
          "actualPrice": 0,
          "actualProductNum": 0,
          "actualProductWeight": 0,
          "head": "string",
          "icon": "string",
          "name": "string",
          "productId": 0,
          "productMode": "string",
          "productNum": 0,
          "productPrice": 0,
          "productTotalPrice": 0,
          "productUnitPrice": 0,
          "productWeight": 0,
          "type": 0,
          "unit": "string"
        }
      ],
      "id": 1,
      "merchantName": "string",
      "orderRemark": "string",
      "paymentAmount": 0,
      "paymentStatus": 0,
      "price": 0,
      "receiverTime": "2017-05-14T11:15:13.353Z",
      "status": 0,
      "statusShowName": "string",
      "totalActualPrice": 0
    }
  ]
}